### PR TITLE
Wrap text in span

### PR DESCRIPTION
**Pull request by fredlesser**
Wraps label text in a span

### CODE REVIEW

**Comment by thhermansen** [comment]
@fredlesser 

I think this component is being used in min side: https://github.com/gramo-org/min-side/search?q=time-input&unscoped_q=time-input. Change is ok for min side?

In echo front the pull request isn't using the template of the component from echo component. It's overridden here: https://github.com/gramo-org/echo-front/pull/1350/files#diff-eaf2b5ac9ce36f91b099d40611b3e2c9

**Comment by fredlesser** [comment]
Change is ok for min side as far as I can see (makes no difference to styling) but could in theory affect tests. Maybe it's better to mod it directly in echo-front?

**Comment by pkrauze** [comment]
I think it can be merged 👍

**Comment by thhermansen** [comment]
> Change is ok for min side as far as I can see (makes no difference to styling) but could in theory affect tests. Maybe it's better to mod it directly in echo-front?

Sounds good. If we are able to have equal HTML for component in echo front too (in other words do not override it's template) I suppose that it would be a plus. I think @fredlesser mentioned that we could try to do that :-)

**Pull request merged**
